overrides:
  - files: '*.yaml'
    options:
      printWidth: 120
      proseWrap: always
      quoteProps: as-needed
      singleQuote: false
  - files: '*.js'
    options:
      printWidth: 120
      singleQuote: true
