PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX ccf: <http://purl.org/ccf/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX CCF: <https://purl.humanatlas.io/graph/ccf>
PREFIX body: <http://purl.obolibrary.org/obo/UBERON_0013702>
PREFIX abdomen: <http://purl.obolibrary.org/obo/UBERON_0005172>
PREFIX has_characterizing_biomarker_set: <http://purl.obolibrary.org/obo/RO_0015004>

CONSTRUCT {
  ?as3d ccf:ccf_3d_part_of ?as3d_parent .
  ?as ccf:ccf_part_of ?as_parent .
  ?ct ccf:ccf_located_in ?ct_as .
  ?ct ccf:ccf_located_in ?ct_as_parent .
  ?child_ct ccf:ccf_located_in ?ct_as .
  ?child_ct ccf:ccf_located_in ?ct_as_parent .
  ?child_ct rdfs:subClassOf ?ct .
  ?bm ccf:ccf_bm_located_in ?bm_as .
  ?bm ccf:ccf_bm_located_in ?bm_as_parent .
}
FROM CCF:
WHERE {
  # {
  #   [] rdf:type ccf:SpatialPlacement ;
  #     ccf:placement_relative_to [
  #       ccf:representation_of ?as3d_parent
  #     ] ;
  #     ccf:placement_for [
  #       ccf:representation_of ?as3d
  #     ] ;
  # }
  # UNION
  # {
  #   ?as ccf:ccf_part_of* ?as_parent .
  # }
  # UNION
  # {
  #   ?ct ccf:ccf_located_in ?ct_as .
  #   ?ct_as ccf:ccf_part_of* ?ct_as_parent .
  #   ?ct ^rdfs:subClassOf* ?child_ct .
  # }
  # UNION
  {
    ?ct ccf:ccf_located_in ?bm_as .
    ?bm_as ccf:ccf_part_of* ?bm_as_parent .

    ?ct rdfs:subClassOf [
      owl:onProperty has_characterizing_biomarker_set: ;
      owl:someValuesFrom [ owl:intersectionOf ?bn3 ]] .
    ?bn3 rdf:rest*/rdf:first [
      owl:onProperty ccf:has_marker_component ;
      owl:someValuesFrom ?bm
    ] .
  }
}
