SELECT ?label ?count
WHERE {
  hint:Query hint:analytic "true" .

  {
    SELECT ("# Nodes" as ?label) (COUNT(DISTINCT(?s)) as ?count)
    WHERE {
      {
        ?s ?p1 [] .
      }
      UNION
      {
        [] ?p2 ?s .
        FILTER(isIRI(?s)) 
      }
    }
  }
  UNION
  {
    SELECT ("# Edges" as ?label) (COUNT(*) as ?count)
    WHERE {
      ?s ?p ?o .
    }
  }
  UNION
  {
    SELECT ("# Edge Types" as ?label) (COUNT(DISTINCT(?p)) as ?count)
    WHERE {
      ?s ?p ?o .
    }
  }
}
